vpn_private_key: ENC[AES256_GCM,data:GoPG5zNmyxq39w/wr94fUNX08/ugVM5jLRp9uzFSQPyql6A+YaqBntLs7Qo=,iv:woA9bYDLjAQwMH13puhSmb1vwsIqmgLxH2uFLkvqWj8=,tag:0wKU2ov2fGQhM1tnZClOoQ==,type:str]
sops:
    age:
        - recipient: age1whpznfrf87er06ya8xxhl23zf97rddk35kuxl53apdyaw6yqmydq0ay99q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWTZMTU1NN0N2RmttTGdi
            V2tjZE83OUkwUURHaExOWEdEYmgvRlVyT0RnCjRxR2VaaTNpTEdEeGl3T1dWWk1s
            WTMxOTdMOXo0U21FY091endpQ1BhOVEKLS0tIFk3b08vYUlpWkFnS2xnTWZld0dT
            S0d6dDJpMngyRDhxUk9MUzBuNnpJdjAK//94sDF6yuq8OTrSgWtrAlsFut+8Txm4
            9uzgsYh98t/pFVBZgjlI4GGQ1UGmj1U9OP2wzUS6yEB5HnKDiirNgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T17:05:15Z"
    mac: ENC[AES256_GCM,data:Eb4akGbMgzH95dGlfr4fzAS7Gtwrl6bXAc5pL1cszoJF+yXUKerHUbjcW9YHLUn/1XCsEa6eAFxVtZjN7qLWpAsoLGT0aX2xbXvTEoQjevZj9mibxehio2/OmOTuqsCxZRwy5J7o1zkzbFGhbpUduJgtkXtFOL+NsiDvFmlnhWg=,iv:s8HNZfvY10chfsYLTOGcrzWaegx2rsgYYkR8uEwfkGI=,tag:zIT2YajaWkUgiSUe7MyFxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
