apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  # Must be in the same namespace as the Traefik pod for now
  # Traefik is both the controller and the router, no reason to seperate them
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 8000 # This is the internal port 'web' in Traefik
      allowedRoutes:
        namespaces:
          from: All # Allow Routes from 'default' namespace to use this Gateway

