---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-creds
  namespace: traefik
spec:
  encryptedData:
    token: AgAgg/hw9v/+nLl6g0KVP1bFK+JkH/LlRP4PZejH59Aifj23hf4iULQnMIv3wJ+bO7XoZO3sSexS1qh+DPcUHqCvlPfsn0T6NLeUK5fl7+sT8wEdWzumknM0nZzD8vP/7YmEKyZvcWEy9y7Eeg5Gm7RH9WkQJeM2L7V6zFXZJP+b/UobA0LE9kRuaktZy/tJWaNn1JMpdDrP/OxQYIowzCK93GqoVC5wLei3cKC2znqKgMKntiihqq5PgI9Tl1i9/glj7k6Npp1ezXP9XOPTK8G2ghig66K4HeRTdlycx+9c4ptKXGud/hqRtEEZBaiLsCClqXOfeHTpLC8RSqaxZ2Q2eAzrscRTVmWUQhvqgwTNL+sAcZ3FdhAfzqoxRJ/3IoR7fW8QMr6GzSIUvyCp8vCu+Ak540uin1fwBwjG2Jngz7KpDULfompRR9SCttDZag3lRRq7hybX2rHQjHEohw7kRyQqXYAbOg/Qeq1V1iSG4BrOQCfk7WTFhyR2Ik16SA0aQ79UZ2nXtKee8+08hVRI2P37fF4NabL5r5yhAgnudVynuxwrsdpcHsDFKuLeo2xUgzTYq7/VtWU6uhTipwvgYt+DAhNnjJyKJNFtoqtgFFKP71VbnBvcrdIQ55u/r1fx674ItghMM5GOmNMYqzb+w+wr5cuxjPVN/ltlBPD+7rcin/IDT5HcutR45KXtvOQ69r9dSErphFG8S0fC44gBf9M+QcSBeA5KkJVxHKSK68HyqNW3S6/7s4gYkGtGmId2SF8+fmxQjx7fM9lYHqr6k2nQyvn+LE5ksl1PJ4C7oXAbHeOUDzSCjTUM5l0WkF2+GlOcnEhzAxMZCdqDZ8B+0EjKyMdUwfZY9W+wzq4ewTJgd7394VWayiYn9cJZDkkKqMi0OnvzRqOZuAY2yFGljc7o6YdYX3JzLuD97EeEi9UDv3rFWxbC
  template:
    metadata:
      name: cloudflared-creds
      namespace: traefik
