tailscale_auth_key: ENC[AES256_GCM,data:eS10Zjyz1JhjSzNMVacog/NFeEJ8z5xP9srZ9TFshigBc6MndoE9UYJyM9l0tXC8jcpiqiQWxDQQZtZdtA==,iv:HSIfnP0e177NDK+Fm6IRBLwxbB/QPxtCha/Ypud0sDo=,tag:tQ2C/eJuwkhn1nYx2hdXPA==,type:str]
sops:
    age:
        - recipient: age1whpznfrf87er06ya8xxhl23zf97rddk35kuxl53apdyaw6yqmydq0ay99q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeXgzdjFJNzZxQzR0Qnkz
            YjNFNGo0N3M4bUo5NUNpaFpCdWcyWWcxQ3p3ClVEUC9iRUEvNWFKOExZMWdQK0xZ
            cWNzUDJzT0hkdEVuMmVFbC8zNkIwM28KLS0tIFhnbjRiMnNHV3R1akJURDI2MTYy
            cml0dVh6c1ZFQ2tEdlJiemlmNWhOVzAK2+PzwmZPQ7BBYyTlNgFeoSN2QvoX9wTV
            t76cVyVFBZpQRYO0AwjMkq/+MQUcxohGujEq8h4pAFgTTZS0UePCzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T18:19:38Z"
    mac: ENC[AES256_GCM,data:shb9MucoSezePeV38ORAahAMkfc0QYDX5licyGFlwogjYab8Q1bVAfQ8dce9agpMthfi7L/ETMFGqa0FuJHmfB5cgUctAcfkwmqq7H+2qUKR2VlmGTCnoIY2mAWxxfBylImDbOGRmjlT8N17GKsiaKy6dTyIJuLxAmJ0yaPPQ3g=,iv:Qre7z6Og8gpN7ht71pUSrgddSZriyp6JhawL6CJ9Z5E=,tag:ej55ncwQBoexYrEQ7nujbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
