---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-tracker-postgres
  namespace: data
spec:
  encryptedData:
    password: AgBbfMqHC1qvlQzHr3mn4secM21YUHFVw1h2oNaXgU7AsizNocsK3VA+NLFZKURa9FtKtOWpACs2SLmwAWH0fZNVXR/u7b1t5DtLI/tqJoo6i29+2nW+1Zww10kEAKdE7ZrW9/6xssDbg0rTGS4OBa3zwEbBVmeG2EeQyb1PyTw8f+DcuG00VHlbi3F+qLO7oHIsSc2VfNg31HGO9XyLGp6q+d5VyriXAH6uvCqLRwv2RpI39vc5f1C0ub03uI40qhwvHQnmUpLCiY/vwC+Gn/vFyr5WtAODwt2/7Q4c4PFUhlWDWdJNfQpzwNRbbQbnbJiliwhjv2+UmIFyo1JDpkdwveuwxE4KyBgMRBPLlrPxCQrezkukSabpM/qBejNILIuztg8xzCLuOyQRlijZ8bxxANN+7tjhTi84iaQyb4g7kVldl6ykYJCki0JNz+fpD3IV81AYdGDpuKDkjNfB/hZPMYUwOzwnSFZqZxdZ49dmd/UNE4Ios7mcVue5KOjC1w+1CIWHUaC922HLXr3/i35iCKksWAqnrEvS1xSxqsR/NRU0tWRMei9RXnI1wQRhSU4w5fkgdYIVManf1VygSDjtZ2a53k08jYcFO91QPD1arRMRigGw3/5ayhVzNjMgQjAEFz7PfksnGloPNPYNSXlrGFKSfjdFFlynd8knMSEwA1TKYUiMWnje1NXUIznS+lzt0ZGjdDSahSmf
    postgres-password: AgBFHDmK7lJgSVwd3o7Ufn5udtENyx8FiY36CAJZrQPDJPB+x4swQhxPFURiDo5vhNbu8zGTMSwzzYH8u9J1EqF4pGAIqgzC+s2/rdPzWJCh4wuEks4+HzR2Ue5bxYV0ISs2vfsXMqj/WYPuZrz18kddlWic3fNIraC4MAxy5anQw/Xl6UomLJ/wtccULag3OaYJUsRl74HcsPF9nawxj/TIL4jtvau/RRKcq4zVuuh50hqJUoziGOnKXlAiDMRQqOdH8IU8KSlza/x4B8glFZMFlbv7wCLA9SoGkQpXQe2x1YBP7yHttErvqgitAtekgrrTOmBVWZ8G4YGO8JnQttUd6oisSk2HSDXZmdj3fPs99QsSBC50f9vMUhPmztjL52cV0/Tgb67snokvfQ4aSWjgWu8vtTkZ8+TIf6AxlFQEo41RQCM8shwDah8Fy/q7bF9fDEC20la0qacoi7l/DFhFk8YJxxdpjrSCnecpKkUyFM/mgR5YywTeeLGxhs6iJlT9kmUZXr1HV8/o+EDZLfvDkect0xv6wiDJ8Z58OzDDXXCUnJBX2uTZoCKmXKQXymBJOEENMpfZQpVjWmCFnGAii3s2227vQteVsVP2Q0of9+STc+B8HLbPDkQL3/5X64qxtRJZKwwCmUP3rq3jU00lF0a1aSt0kghqnQeEBCDSDU5ZWqK1nm0oEZpaNGydi+p4VDgd5/PKdNTAuv8G
  template:
    metadata:
      name: media-tracker-postgres
      namespace: data
    type: Opaque
