apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-tracker-app
  namespace: default
  labels:
    app: media-tracker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-tracker-app
  template:
    metadata:
      labels:
        app: media-tracker-app
    spec:
      containers:
        - name: app
          image: socknot1000kg/media-tracker-backend:0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000 # app's internal port
          env:
            - name: NODE_ENV
              value: "production"
            - name: RATE_LIMIT_ENABLED
              value: "true"
            - name: VERSION
              value: "0.1"
          envFrom:
            - secretRef:
                name: media-tracker-secret
