apiVersion: v1
kind: Service
metadata:
  name: media-tracker-svc
  namespace: default
spec:
  ports:
    - port: 80 # Service Port
      targetPort: 5000 # Container Port
  selector:
    app: media-tracker-app
